config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get 'home'    => 'static_pages#home'
  get 'help'   => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'edit'  => 'users#edit'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers  #since both showing data
    end
  end  
  
  resources :users #methods such as delete are implicit
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  
  
  mount Rapidfire::Engine => "/rapidfire"

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
    This is the about page.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %> 
<h1>Contact</h1> 
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<nav class="breadcrumbs z-depth-1" style="z-index: -1; background-color: rgba(227,242,253,.5); height: 20px; border-radius: 0px; margin-top: -20px;">
  <a class="unavailable" href="/help/">Help</a>
</nav>  

<% provide(:title, "Help") %>
<h1>Help</h1>


  <ul class="collapsible popout" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="material-icons">filter_drama</i>Logging in</div>
      <div class="collapsible-body"><p>Receive your login information (one per team).<br>
      <%= link_to "Login", login_path, :class => "waves-effect waves-teal btn-flat btn item", :id => "" %> using provided username and password.</p>
      </div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">place</i>The Hunt</div>
      <div class="collapsible-body"><p> 
            <%= link_to "Question Groups", rapidfire_path, :class => "waves-effect waves-teal btn-flat btn item", :id => "" %> are based on location. Choose where you are hunting and click 'Answer Questions'
            <br><br>Multiple people can be logged into the same team account, so how you work together to win is up to you.
            <br><br>If you decide to split up, remember that you have to meet back up to input all answers on one device.
      </p>
      </div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">whatshot</i>Teams</div>
      <div class="collapsible-body"><p><%= link_to "Teams", root_path, :class => "waves-effect waves-teal btn-flat btn item", :id => "" %> are automatically assigned to follow all other teams, so you will see live updates of how the others are doing.
      <br><br>When you submit answers, it is evaluated and auto-posted for everyone to see (&#9989 or &#10060 in the same question order).
      <br><br>Feel free to talk smack to other teams, as well as post pictures.
      
      </p></div>
    </li>
  </ul>
  
  
  
  <script>
  $(document).ready(function(){
    $('.collapsible').collapsible({
      accordion : false // A setting that changes the collapsible behavior to expandable instead of the default accordion style
    });
  });      
  </script>

app/views/static_pages/home.html.erb
<% if logged_in? %>
<nav class="breadcrumbs z-depth-1" style="z-index: -1; background-color: rgba(227,242,253,.5); height: 20px; border-radius: 0px; margin-top: -20px;">
  <a class="unavailable" href="/">Teams</a>
</nav>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Team Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
<div class="center jumbotron">
  <h1>Welcome to Frosh Week</h1>

  <h5>
    This is the home page for the
    <a href="https://www.cshub.ca/"><%= image_tag "cshub_logo.png", size: "300" %></a>
    Scavenger Hunt application.
  </h5>
  
  <h5>Please  <%= link_to "Login", login_path, :class => "item" %> with the provided credentials. </h5>

  <%= link_to "Sign up now!", signup_path, class: "button large" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>
<% end %>